# http://www.appveyor.com/docs/appveyor-yml
branches:
  only:
    - master
    - develop
    - /\d*\.\d*\.\d*/

image: Visual Studio 2019
test: off

install:
  - cinst dotnetcore-sdk --version 3.1.202

build_script:
  - ps: .\build.ps1 CI -Verbose

artifacts:
  - path: \artifacts\*.*

nuget:
  disable_publish_on_pr: true

skip_commits:
  files:
    - '**/*.md'